In [2]:
import torch
import pandas as pd
import numpy as np
print(torch.__version__)

2.0.1


### Introduction to Tensors
Creating tensors

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
#Get tensor back as Python List
scalar.item()

7

In [6]:
#Vector
vector = torch.tensor([7,7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                        [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [16]:
ten = torch.tensor([[[10,2,30],[21,23,43],[312,32,43]]])
ten

tensor([[[ 10,   2,  30],
         [ 21,  23,  43],
         [312,  32,  43]]])

### Random Tensors
Why Random Tensors?

Random tensors are important because the way many neural networks learn is that they start with tensor full of random numbers and then adjust those numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors- https://pytorch.org/docs/stable/generated/torch.rand.html

In [17]:
#Create a random tensor of size (3,4)
random_tensor = torch.rand(3,3,4)
random_tensor

tensor([[[0.3366, 0.7118, 0.9740, 0.4711],
         [0.8685, 0.7072, 0.4998, 0.9104],
         [0.6717, 0.6426, 0.2603, 0.4338]],

        [[0.0265, 0.6680, 0.2395, 0.5506],
         [0.6781, 0.1311, 0.8158, 0.8026],
         [0.5718, 0.2451, 0.0034, 0.6994]],

        [[0.1900, 0.9682, 0.6879, 0.5040],
         [0.0427, 0.3236, 0.8231, 0.1297],
         [0.2955, 0.9864, 0.8088, 0.9764]]])

In [18]:
random_tensor.ndim

3

In [19]:
random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, channels(R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeroes and Ones

In [20]:
#Create a tensor of all zeroes
zeroes = torch.zeros(size=(4,5))
zeroes

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [21]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [23]:
#Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
#Creating tensor like
ten_zeroes = torch.zeros_like(input= one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

**Note:** Tensor datatypes is one of the main 3 big errors you'll get into with PyTorch & Deep Learning:

1. Tensors not right datatype

2. Tensor not on right shape

3. Tensor not on right device

In [25]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, #what datatype is the tensor (e.g. float32 or float16)
                               device = None, #What device is your tensor on
                               requires_grad= False
                               )
                                #whether or not to track gradients with this tensors operatons
float_32_tensor

tensor([3., 6., 9.])

In [26]:
float_32_tensor.dtype

torch.float32

In [27]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [28]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [29]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [30]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors(tensor attributes)

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`

2. Tensors not on right shape  - to get shape from a tensor, can use `tensor.shape`

3. Tensor not on right device - to get device from a tensor, can use `tensor.device`

In [31]:
#Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.8104, 0.9112, 0.7013, 0.6568],
        [0.4674, 0.9170, 0.6879, 0.4845],
        [0.2606, 0.8062, 0.4487, 0.5691]])

In [32]:
#Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.size}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.8104, 0.9112, 0.7013, 0.6568],
        [0.4674, 0.9170, 0.6879, 0.4845],
        [0.2606, 0.8062, 0.4487, 0.5691]])
Datatype of tensor: torch.float32
Shape of tensor: <built-in method size of Tensor object at 0x17b27b8e0>
Device tensor is on: cpu


### Manipulating Tensors(tensor operations)

Tensor operations inclued:

* Addition
* Subtraction
* Multiplication(element-wise)
* Division
* Matrix Multiplicaiton

In [33]:
#Create a tensor and add
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [34]:
#Tensor Multiplication
tensor * 10

tensor([10, 20, 30])

In [35]:
tensor

tensor([1, 2, 3])

In [36]:
#Tensor Subtraction
tensor - 10

tensor([-9, -8, -7])

In [37]:
#Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix Multiplication
Two main ways of performing multiplicaiton in neural networks and deep learning:

1. Element-Wise multiplication
2. Matrix Multiplication (dot product)

More info on multiplying - https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplication needs to satisfy:

1. The **inner dimesions** must match:

* `(3,2) @ (3,2) won't work`
* `(2,3) @ (3,2) will work`
* `(3,2) @ (2,3) will work`

2. The resulting matrix has the sahpe of the **Outer Dimensions:**
* `(2,3) @ (3,2) -> (2,2)`
* `(3,2) @ (2,3) -> (3,3)`

In [38]:
#Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [39]:
#Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [40]:
#Matrix Multiplication By Hand
1*1 + 2*2 + 3*3

14

In [41]:
%%time
value = 0
for i in range(len(tensor)):
 value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 611 µs, sys: 735 µs, total: 1.35 ms
Wall time: 795 µs


In [42]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 23 µs, sys: 2 µs, total: 25 µs
Wall time: 26.9 µs


tensor(14)

### One of the most common errors in deep learning: Shape Errors

In [43]:
#Shape for Matrix Multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

#torch.mm(tensor_A, tensor_B) #tensor.mm is the same as torch.matmul (it's an alias for writing less code)
#toch.matmul(tensor_A, tensor_B)

To fix a tensor shape issue, we can manipulate the shape of our tensor using a **transpose**.

A **Transpose** switches the axes or dimensions of a given tensor.

In [44]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [45]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [46]:
torch.matmul(tensor_A, tensor_B.T).shape #here (tensor_B.T) "T" is used for Transpose

torch.Size([3, 3])

In [47]:
#The matrix multiplication operation works when tensor_B is transposed
print(f"Original shape of tensor_A: {tensor_A.shape}, tensor_B: {tensor_B.shape}")
print(f"New Shape: tensor_A: {tensor_A.shape}, same shape as above, tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.shape} <- Inner Dimension must watch")
print(f"Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shape of tensor_A: torch.Size([3, 2]), tensor_B: torch.Size([3, 2])
New Shape: tensor_A: torch.Size([3, 2]), same shape as above, tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([3, 2]) <- Inner Dimension must watch
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


### Just for practice Matrix Multiplication

In [48]:
#shape for matrix multiplication
tensor_C = torch.tensor([[3,2],[4,6],[6,7]])
tensor_D = torch.tensor([[4,10],[23,43],[2,4]])
#torch.matmul(tensor_C,tensor_D)

In [49]:
tensor_C.T

tensor([[3, 4, 6],
        [2, 6, 7]])

In [50]:
tensor_C.T.shape

torch.Size([2, 3])

In [51]:
update_tensors = torch.matmul(tensor_C.T, tensor_D)

In [52]:
print(update_tensors)

tensor([[116, 226],
        [160, 306]])


In [53]:
update_tensors.shape

torch.Size([2, 2])

In [54]:
tensor_D.shape

torch.Size([3, 2])

So the above matrix is transformed into the shape of 2X2 because they have to match the shape of outer dimensions in the final output

### Finding the Min, Max, Mean, Sum, ETC(Tensor Aggregation)

In [55]:
#Create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [56]:
#Find the Min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [57]:
#Find the Max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [58]:
#Find the Mean - note: the torch.mean() requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32))

tensor(45.)

In [59]:
#Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional Min and Max

In [60]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [61]:
#Find the position in tensor that has the minimum value with argmin() -> returns the position of target tensor where the minimum value occurs
torch.argmin(x)

tensor(0)

In [62]:
#Finding the position in tensor that has the maximum value with argmax() -> returns the position of target where the maximum value occurs
torch.argmax(x)

tensor(9)

### Reshaping, Stacking, Squeezing and Unsqueezing Tensors

* Reshaping - reshapes an input to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as original tensor
* Stacking - combines multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - remove all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [1]:
#Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))