In [2]:
import torch
import pandas as pd
import numpy as np
print(torch.__version__)

2.0.1


### Introduction to Tensors
Creating tensors

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
#Get tensor back as Python List
scalar.item()

7

In [6]:
#Vector
vector = torch.tensor([7,7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                        [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [16]:
ten = torch.tensor([[[10,2,30],[21,23,43],[312,32,43]]])
ten

tensor([[[ 10,   2,  30],
         [ 21,  23,  43],
         [312,  32,  43]]])

### Random Tensors
Why Random Tensors?

Random tensors are important because the way many neural networks learn is that they start with tensor full of random numbers and then adjust those numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors- https://pytorch.org/docs/stable/generated/torch.rand.html

In [17]:
#Create a random tensor of size (3,4)
random_tensor = torch.rand(3,3,4)
random_tensor

tensor([[[0.0275, 0.7085, 0.2270, 0.6532],
         [0.0816, 0.1649, 0.4292, 0.0654],
         [0.2860, 0.6827, 0.1129, 0.9995]],

        [[0.7299, 0.6246, 0.1829, 0.9695],
         [0.4274, 0.3684, 0.8415, 0.0792],
         [0.4246, 0.1380, 0.3177, 0.8804]],

        [[0.9562, 0.8192, 0.2085, 0.4099],
         [0.1818, 0.6520, 0.5607, 0.3108],
         [0.3123, 0.3407, 0.5049, 0.8250]]])

In [18]:
random_tensor.ndim

3

In [19]:
random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, channels(R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeroes and Ones

In [21]:
#Create a tensor of all zeroes
zeroes = torch.zeros(size=(4,5))
zeroes

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [23]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [25]:
#Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
#Creating tensor like
ten_zeroes = torch.zeros_like(input= one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

**Note:** Tensor datatypes is one of the main 3 big errors you'll get into with PyTorch & Deep Learning:

1. Tensors not right datatype

2. Tensor not on right shape

3. Tensor not on right device

In [27]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, #what datatype is the tensor (e.g. float32 or float16)
                               device = None, #What device is your tensor on
                               requires_grad= False
                               )
                                #whether or not to track gradients with this tensors operatons
float_32_tensor

tensor([3., 6., 9.])

In [28]:
float_32_tensor.dtype

torch.float32

In [29]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [30]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [31]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [32]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors(tensor attributes)

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`

2. Tensors not on right shape  - to get shape from a tensor, can use `tensor.shape`

3. Tensor not on right device - to get device from a tensor, can use `tensor.device`

In [33]:
#Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4031, 0.7488, 0.0106, 0.9055],
        [0.3079, 0.4930, 0.1751, 0.9010],
        [0.5411, 0.4956, 0.8448, 0.5256]])

In [34]:
#Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.size}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.4031, 0.7488, 0.0106, 0.9055],
        [0.3079, 0.4930, 0.1751, 0.9010],
        [0.5411, 0.4956, 0.8448, 0.5256]])
Datatype of tensor: torch.float32
Shape of tensor: <built-in method size of Tensor object at 0x15b763570>
Device tensor is on: cpu


### Manipulating Tensors(tensor operations)

Tensor operations inclued:

* Addition
* Subtraction
* Multiplication(element-wise)
* Division
* Matrix Multiplicaiton

In [35]:
#Create a tensor and add
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [36]:
#Tensor Multiplication
tensor * 10

tensor([10, 20, 30])

In [37]:
tensor

tensor([1, 2, 3])

In [38]:
#Tensor Subtraction
tensor - 10

tensor([-9, -8, -7])

In [39]:
#Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix Multiplication
Two main ways of performing multiplicaiton in neural networks and deep learning:

1. Element-Wise multiplication
2. Matrix Multiplication (dot product)

More info on multiplying - https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplication needs to satisfy:

1. The **inner dimesions** must match:

* `(3,2) @ (3,2) won't work`
* `(2,3) @ (3,2) will work`
* `(3,2) @ (2,3) will work`

2. The resulting matrix has the sahpe of the **Outer Dimensions:**
* `(2,3) @ (3,2) -> (2,2)`
* `(3,2) @ (2,3) -> (3,3)`