In [1]:
import torch
import pandas as pd
import numpy as np
print(torch.__version__)

2.0.1


### Introduction to Tensors
Creating tensors

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [ ]:
#Get tensor back as Python List
scalar.item()

In [5]:
#Vector
vector = torch.tensor([7,7])

In [6]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [14]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                        [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [15]:
MATRIX.ndim

2

In [16]:
MATRIX.shape

torch.Size([2, 2])

In [17]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [18]:
TENSOR.ndim

3

In [19]:
TENSOR.shape

torch.Size([1, 3, 3])

In [20]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [21]:
ten = torch.tensor([[[10,2,30],[21,23,43],[312,32,43]]])
ten

tensor([[[ 10,   2,  30],
         [ 21,  23,  43],
         [312,  32,  43]]])