In [1]:
import torch
import pandas as pd
import numpy as np
print(torch.__version__)

2.0.1


### Introduction to Tensors
Creating tensors

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [ ]:
#Get tensor back as Python List
scalar.item()

In [5]:
#Vector
vector = torch.tensor([7,7])

In [6]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [14]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                        [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [15]:
MATRIX.ndim

2

In [16]:
MATRIX.shape

torch.Size([2, 2])

In [17]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [18]:
TENSOR.ndim

3

In [19]:
TENSOR.shape

torch.Size([1, 3, 3])

In [20]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [21]:
ten = torch.tensor([[[10,2,30],[21,23,43],[312,32,43]]])
ten

tensor([[[ 10,   2,  30],
         [ 21,  23,  43],
         [312,  32,  43]]])

### Random Tensors
Why Random Tensors?

Random tensors are important because the way many neural networks learn is that they start with tensor full of random numbers and then adjust those numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors- https://pytorch.org/docs/stable/generated/torch.rand.html

In [22]:
#Create a random tensor of size (3,4)
random_tensor = torch.rand(3,3,4)
random_tensor

tensor([[[0.9298, 0.6254, 0.1312, 0.3211],
         [0.4908, 0.0641, 0.0518, 0.8818],
         [0.5771, 0.9017, 0.7321, 0.9649]],

        [[0.4350, 0.6561, 0.7674, 0.5292],
         [0.3085, 0.5992, 0.8826, 0.2732],
         [0.3016, 0.9537, 0.3552, 0.2771]],

        [[0.4943, 0.2800, 0.1417, 0.8567],
         [0.1977, 0.9519, 0.4860, 0.2926],
         [0.8645, 0.7428, 0.0694, 0.0537]]])

In [23]:
random_tensor.ndim

3

In [24]:
random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, channels(R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)